liquibase:
  change-log: classpath:liquibase/master.xml
spring:
  datasource:
    url: jdbc:h2:file:./target/h2db/db/demodb;DB_CLOSE_DELAY=-1
  thymeleaf:
    reactive:
      max-chunk-size: 8192
  h2:
    console:
      enabled: true
  jackson:
    parser:
  profiles:
    active: live
  jpa:
    hibernate:
      ddl-auto: validate
gitter:
  api:
    endpoint: https://stream.gitter.im/
    messages-resource: rooms/596a67f6d73408ce4f6d4f66/chatMessages
    auth:
      token: ${GITTER_TOKEN}
